/*
 * JSpeccy.java
 *
 * Created on 21 de enero de 2008, 14:27
 */

package gui;

import java.awt.BorderLayout;
import java.io.File;
import java.util.ResourceBundle;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.plaf.basic.BasicFileChooserUI;
import machine.Spectrum;

/**
 *
 * @author  jsanchez
 */
public class JSpeccy extends javax.swing.JFrame {
    Spectrum spectrum;
    JSpeccyScreen jscr;
    File currentDirOpenSnapshot, currentDirSaveSnapshot, currentDirTape;
    JFileChooser openSnapshotDlg, saveSnapshotDlg, OpenTapeDlg;
    ListSelectionModel lsm;
    /** Creates new form JSpeccy */
    public JSpeccy() {
        initComponents();
        spectrum = new Spectrum();
        jscr = new JSpeccyScreen();
        spectrum.setScreenComponent(jscr);
        jscr.setTvImage(spectrum.getTvImage());
        spectrum.setInfoLabels(modelLabel, speedLabel);
        spectrum.setHardwareMenuItems(spec48kHardware, spec128kHardware);
        spectrum.setJoystickMenuItems(noneJoystick, kempstonJoystick,
            sinclair1Joystick, sinclair2Joystick, cursorJoystick);
        spectrum.tape.setTapeIcon(tapeLabel);
        tapeCatalog.setModel(spectrum.tape.getTapeTableModel());
        tapeCatalog.getColumnModel().getColumn(0).setMaxWidth(150);
        lsm = tapeCatalog.getSelectionModel();
        lsm.addListSelectionListener(new TapeBrowserSelectionListener(spectrum.tape));
        getContentPane().add(jscr,BorderLayout.CENTER);
        pack();
        addKeyListener(spectrum.getKeyboard());
        spectrum.start();
        spectrum.startEmulation();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        keyboardHelper = new javax.swing.JDialog(this);
        keyboardImage = new javax.swing.JLabel();
        closeKeyboardHelper = new javax.swing.JButton();
        joystickButtonGroup = new javax.swing.ButtonGroup();
        hardwareButtonGroup = new javax.swing.ButtonGroup();
        tapeBrowserDialog = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tapeCatalog = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        closeTapeBrowserButton = new javax.swing.JButton();
        tapeFilename = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        modelLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tapeLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        speedLabel = new javax.swing.JLabel();
        toolbarMenu = new javax.swing.JToolBar();
        openSnapshotButton = new javax.swing.JButton();
        pauseToggleButton = new javax.swing.JToggleButton();
        fastEmulationToggleButton = new javax.swing.JToggleButton();
        doubleSizeToggleButton = new javax.swing.JToggleButton();
        silenceSoundToggleButton = new javax.swing.JToggleButton();
        resetSpectrumButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        fileOpenSnapshot = new javax.swing.JMenuItem();
        fileSaveSnapshot = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        thisIsTheEndMyFriend = new javax.swing.JMenuItem();
        optionsMenu = new javax.swing.JMenu();
        doubleSizeOption = new javax.swing.JCheckBoxMenuItem();
        joystickOptionMenu = new javax.swing.JMenu();
        noneJoystick = new javax.swing.JRadioButtonMenuItem();
        kempstonJoystick = new javax.swing.JRadioButtonMenuItem();
        sinclair1Joystick = new javax.swing.JRadioButtonMenuItem();
        sinclair2Joystick = new javax.swing.JRadioButtonMenuItem();
        cursorJoystick = new javax.swing.JRadioButtonMenuItem();
        machineMenu = new javax.swing.JMenu();
        pauseMachineMenu = new javax.swing.JCheckBoxMenuItem();
        silenceMachineMenu = new javax.swing.JCheckBoxMenuItem();
        resetMachineMenu = new javax.swing.JMenuItem();
        nmiMachineMenu = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        hardwareMachineMenu = new javax.swing.JMenu();
        spec48kHardware = new javax.swing.JRadioButtonMenuItem();
        spec128kHardware = new javax.swing.JRadioButtonMenuItem();
        mediaMenu = new javax.swing.JMenu();
        tapeMediaMenu = new javax.swing.JMenu();
        openTapeMediaMenu = new javax.swing.JMenuItem();
        playTapeMediaMenu = new javax.swing.JMenuItem();
        browserTapeMediaMenu = new javax.swing.JMenuItem();
        rewindTapeMediaMenu = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        imageHelpMenu = new javax.swing.JMenuItem();
        aboutHelpMenu = new javax.swing.JMenuItem();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("gui/Bundle"); // NOI18N
        keyboardHelper.setTitle(bundle.getString("JSpeccy.keyboardHelper.title")); // NOI18N

        keyboardImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Spectkey.png"))); // NOI18N
        keyboardImage.setText(bundle.getString("JSpeccy.keyboardImage.text")); // NOI18N
        keyboardHelper.getContentPane().add(keyboardImage, java.awt.BorderLayout.PAGE_START);

        closeKeyboardHelper.setText(bundle.getString("JSpeccy.closeKeyboardHelper.text")); // NOI18N
        closeKeyboardHelper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeKeyboardHelperActionPerformed(evt);
            }
        });
        keyboardHelper.getContentPane().add(closeKeyboardHelper, java.awt.BorderLayout.PAGE_END);

        joystickButtonGroup.add(noneJoystick);
        joystickButtonGroup.add(kempstonJoystick);
        joystickButtonGroup.add(sinclair1Joystick);
        joystickButtonGroup.add(sinclair2Joystick);
        joystickButtonGroup.add(cursorJoystick);

        hardwareButtonGroup.add(spec48kHardware);
        hardwareButtonGroup.add(spec128kHardware);

        tapeBrowserDialog.setTitle(bundle.getString("JSpeccy.tapeBrowserDialog.title")); // NOI18N

        tapeCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Block Number", "Block Type", "Block information"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tapeCatalog.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tapeCatalog.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tapeCatalog.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tapeCatalog);
        tapeCatalog.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tapeCatalog.getColumnModel().getColumn(0).setResizable(false);
        tapeCatalog.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("JSpeccy.tapeCatalog.columnModel.title0")); // NOI18N
        tapeCatalog.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("JSpeccy.tapeCatalog.columnModel.title1")); // NOI18N
        tapeCatalog.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("JSpeccy.tapeCatalog.columnModel.title2")); // NOI18N

        tapeBrowserDialog.getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        closeTapeBrowserButton.setText(bundle.getString("JSpeccy.closeTapeBrowserButton.text")); // NOI18N
        closeTapeBrowserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeTapeBrowserButtonActionPerformed(evt);
            }
        });
        jPanel2.add(closeTapeBrowserButton);

        tapeBrowserDialog.getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        tapeFilename.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tapeFilename.setText(bundle.getString("JSpeccy.tapeFilename.text")); // NOI18N
        tapeBrowserDialog.getContentPane().add(tapeFilename, java.awt.BorderLayout.PAGE_START);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(bundle.getString("JSpeccy.title")); // NOI18N
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        modelLabel.setText(bundle.getString("JSpeccy.modelLabel.text")); // NOI18N
        modelLabel.setToolTipText(bundle.getString("JSpeccy.modelLabel.toolTipText")); // NOI18N
        modelLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(modelLabel);

        jLabel1.setText(bundle.getString("JSpeccy.jLabel1.text")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(32767, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel1.add(jLabel1);

        tapeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tapeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Akai24x24.png"))); // NOI18N
        tapeLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tapeLabel.setEnabled(false);
        tapeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tapeLabel.setPreferredSize(new java.awt.Dimension(36, 26));
        tapeLabel.setRequestFocusEnabled(false);
        jPanel1.add(tapeLabel);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setMaximumSize(new java.awt.Dimension(5, 32767));
        jSeparator2.setMinimumSize(new java.awt.Dimension(3, 16));
        jSeparator2.setPreferredSize(new java.awt.Dimension(3, 16));
        jSeparator2.setRequestFocusEnabled(false);
        jPanel1.add(jSeparator2);

        speedLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        speedLabel.setText(bundle.getString("JSpeccy.speedLabel.text")); // NOI18N
        speedLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        speedLabel.setPreferredSize(new java.awt.Dimension(40, 18));
        speedLabel.setRequestFocusEnabled(false);
        jPanel1.add(speedLabel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        toolbarMenu.setRollover(true);

        openSnapshotButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fileopen.png"))); // NOI18N
        openSnapshotButton.setToolTipText(bundle.getString("JSpeccy.openSnapshotButton.toolTipText")); // NOI18N
        openSnapshotButton.setFocusable(false);
        openSnapshotButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openSnapshotButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        openSnapshotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileOpenSnapshotActionPerformed(evt);
            }
        });
        toolbarMenu.add(openSnapshotButton);

        pauseToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/player_pause.png"))); // NOI18N
        pauseToggleButton.setToolTipText(bundle.getString("JSpeccy.pauseToggleButton.toolTipText")); // NOI18N
        pauseToggleButton.setFocusable(false);
        pauseToggleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pauseToggleButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/player_play.png"))); // NOI18N
        pauseToggleButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pauseToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseMachineMenuActionPerformed(evt);
            }
        });
        toolbarMenu.add(pauseToggleButton);

        fastEmulationToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/player_fwd.png"))); // NOI18N
        fastEmulationToggleButton.setText(bundle.getString("JSpeccy.fastEmulationToggleButton.text")); // NOI18N
        fastEmulationToggleButton.setToolTipText(bundle.getString("JSpeccy.fastEmulationToggleButton.toolTipText")); // NOI18N
        fastEmulationToggleButton.setFocusable(false);
        fastEmulationToggleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fastEmulationToggleButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        fastEmulationToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fastEmulationToggleButtonActionPerformed(evt);
            }
        });
        toolbarMenu.add(fastEmulationToggleButton);

        doubleSizeToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/viewmag+.png"))); // NOI18N
        doubleSizeToggleButton.setToolTipText(bundle.getString("JSpeccy.doubleSizeToggleButton.toolTipText")); // NOI18N
        doubleSizeToggleButton.setFocusable(false);
        doubleSizeToggleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        doubleSizeToggleButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/viewmag-.png"))); // NOI18N
        doubleSizeToggleButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        doubleSizeToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleSizeOptionActionPerformed(evt);
            }
        });
        toolbarMenu.add(doubleSizeToggleButton);

        silenceSoundToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sound-on-16x16.png"))); // NOI18N
        silenceSoundToggleButton.setToolTipText(bundle.getString("JSpeccy.silenceSoundToggleButton.toolTipText")); // NOI18N
        silenceSoundToggleButton.setFocusable(false);
        silenceSoundToggleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        silenceSoundToggleButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sound-off-16x16.png"))); // NOI18N
        silenceSoundToggleButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        silenceSoundToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silenceSoundToggleButtonActionPerformed(evt);
            }
        });
        toolbarMenu.add(silenceSoundToggleButton);

        resetSpectrumButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shutdown.png"))); // NOI18N
        resetSpectrumButton.setToolTipText(bundle.getString("JSpeccy.resetSpectrumButton.toolTipText")); // NOI18N
        resetSpectrumButton.setFocusable(false);
        resetSpectrumButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resetSpectrumButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        resetSpectrumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetMachineMenuActionPerformed(evt);
            }
        });
        toolbarMenu.add(resetSpectrumButton);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        exitButton.setToolTipText(bundle.getString("JSpeccy.exitButton.toolTipText")); // NOI18N
        exitButton.setFocusable(false);
        exitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thisIsTheEndMyFriendActionPerformed(evt);
            }
        });
        toolbarMenu.add(exitButton);

        getContentPane().add(toolbarMenu, java.awt.BorderLayout.PAGE_START);

        fileMenu.setText(bundle.getString("JSpeccy.fileMenu.text")); // NOI18N

        fileOpenSnapshot.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        fileOpenSnapshot.setText(bundle.getString("JSpeccy.fileOpenSnapshot.text")); // NOI18N
        fileOpenSnapshot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileOpenSnapshotActionPerformed(evt);
            }
        });
        fileMenu.add(fileOpenSnapshot);

        fileSaveSnapshot.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        fileSaveSnapshot.setText(bundle.getString("JSpeccy.fileSaveSnapshot.text")); // NOI18N
        fileSaveSnapshot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileSaveSnapshotActionPerformed(evt);
            }
        });
        fileMenu.add(fileSaveSnapshot);
        fileMenu.add(jSeparator1);

        thisIsTheEndMyFriend.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        thisIsTheEndMyFriend.setText(bundle.getString("JSpeccy.thisIsTheEndMyFriend.text")); // NOI18N
        thisIsTheEndMyFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thisIsTheEndMyFriendActionPerformed(evt);
            }
        });
        fileMenu.add(thisIsTheEndMyFriend);

        jMenuBar1.add(fileMenu);

        optionsMenu.setText(bundle.getString("JSpeccy.optionsMenu.text")); // NOI18N

        doubleSizeOption.setText(bundle.getString("JSpeccy.doubleSizeOption.text")); // NOI18N
        doubleSizeOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleSizeOptionActionPerformed(evt);
            }
        });
        optionsMenu.add(doubleSizeOption);

        joystickOptionMenu.setText(bundle.getString("JSpeccy.joystickOptionMenu.text")); // NOI18N

        noneJoystick.setSelected(true);
        noneJoystick.setText(bundle.getString("JSpeccy.noneJoystick.text")); // NOI18N
        noneJoystick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noneJoystickActionPerformed(evt);
            }
        });
        joystickOptionMenu.add(noneJoystick);

        kempstonJoystick.setText(bundle.getString("JSpeccy.kempstonJoystick.text")); // NOI18N
        kempstonJoystick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kempstonJoystickActionPerformed(evt);
            }
        });
        joystickOptionMenu.add(kempstonJoystick);

        sinclair1Joystick.setText(bundle.getString("JSpeccy.sinclair1Joystick.text")); // NOI18N
        sinclair1Joystick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinclair1JoystickActionPerformed(evt);
            }
        });
        joystickOptionMenu.add(sinclair1Joystick);

        sinclair2Joystick.setText(bundle.getString("JSpeccy.sinclair2Joystick.text")); // NOI18N
        sinclair2Joystick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinclair2JoystickActionPerformed(evt);
            }
        });
        joystickOptionMenu.add(sinclair2Joystick);

        cursorJoystick.setText(bundle.getString("JSpeccy.cursorJoystick.text")); // NOI18N
        cursorJoystick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursorJoystickActionPerformed(evt);
            }
        });
        joystickOptionMenu.add(cursorJoystick);

        optionsMenu.add(joystickOptionMenu);

        jMenuBar1.add(optionsMenu);

        machineMenu.setText(bundle.getString("JSpeccy.machineMenu.text")); // NOI18N
        machineMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silenceSoundToggleButtonActionPerformed(evt);
            }
        });

        pauseMachineMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_PAUSE, 0));
        pauseMachineMenu.setText(bundle.getString("JSpeccy.pauseMachineMenu.text")); // NOI18N
        pauseMachineMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseMachineMenuActionPerformed(evt);
            }
        });
        machineMenu.add(pauseMachineMenu);

        silenceMachineMenu.setText(bundle.getString("JSpeccy.silenceMachineMenu.text")); // NOI18N
        silenceMachineMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silenceSoundToggleButtonActionPerformed(evt);
            }
        });
        machineMenu.add(silenceMachineMenu);

        resetMachineMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        resetMachineMenu.setText(bundle.getString("JSpeccy.resetMachineMenu.text")); // NOI18N
        resetMachineMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetMachineMenuActionPerformed(evt);
            }
        });
        machineMenu.add(resetMachineMenu);

        nmiMachineMenu.setText(bundle.getString("JSpeccy.nmiMachineMenu.text")); // NOI18N
        nmiMachineMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmiMachineMenuActionPerformed(evt);
            }
        });
        machineMenu.add(nmiMachineMenu);
        machineMenu.add(jSeparator3);

        hardwareMachineMenu.setText(bundle.getString("JSpeccy.hardwareMachineMenu.text")); // NOI18N

        spec48kHardware.setSelected(true);
        spec48kHardware.setText(bundle.getString("JSpeccy.spec48kHardware.text")); // NOI18N
        spec48kHardware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spec48kHardwareActionPerformed(evt);
            }
        });
        hardwareMachineMenu.add(spec48kHardware);

        spec128kHardware.setText(bundle.getString("JSpeccy.spec128kHardware.text")); // NOI18N
        spec128kHardware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spec128kHardwareActionPerformed(evt);
            }
        });
        hardwareMachineMenu.add(spec128kHardware);

        machineMenu.add(hardwareMachineMenu);

        jMenuBar1.add(machineMenu);

        mediaMenu.setText(bundle.getString("JSpeccy.mediaMenu.text")); // NOI18N

        tapeMediaMenu.setText(bundle.getString("JSpeccy.tapeMediaMenu.text")); // NOI18N

        openTapeMediaMenu.setText(bundle.getString("JSpeccy.openTapeMediaMenu.text")); // NOI18N
        openTapeMediaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openTapeMediaMenuActionPerformed(evt);
            }
        });
        tapeMediaMenu.add(openTapeMediaMenu);

        playTapeMediaMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        playTapeMediaMenu.setText(bundle.getString("JSpeccy.playTapeMediaMenu.text")); // NOI18N
        playTapeMediaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playTapeMediaMenuActionPerformed(evt);
            }
        });
        tapeMediaMenu.add(playTapeMediaMenu);

        browserTapeMediaMenu.setText(bundle.getString("JSpeccy.browserTapeMediaMenu.text")); // NOI18N
        browserTapeMediaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browserTapeMediaMenuActionPerformed(evt);
            }
        });
        tapeMediaMenu.add(browserTapeMediaMenu);

        rewindTapeMediaMenu.setText(bundle.getString("JSpeccy.rewindTapeMediaMenu.text")); // NOI18N
        rewindTapeMediaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rewindTapeMediaMenuActionPerformed(evt);
            }
        });
        tapeMediaMenu.add(rewindTapeMediaMenu);

        mediaMenu.add(tapeMediaMenu);

        jMenuBar1.add(mediaMenu);

        helpMenu.setText(bundle.getString("JSpeccy.helpMenu.text")); // NOI18N

        imageHelpMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        imageHelpMenu.setText(bundle.getString("JSpeccy.imageHelpMenu.text")); // NOI18N
        imageHelpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageHelpMenuActionPerformed(evt);
            }
        });
        helpMenu.add(imageHelpMenu);

        aboutHelpMenu.setText(bundle.getString("JSpeccy.aboutHelpMenu.text")); // NOI18N
        aboutHelpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutHelpMenuActionPerformed(evt);
            }
        });
        helpMenu.add(aboutHelpMenu);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileOpenSnapshotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileOpenSnapshotActionPerformed
        // TODO add your handling code here:
        boolean paused = spectrum.isPaused();
        if( openSnapshotDlg == null ) {
            openSnapshotDlg = new JFileChooser("/home/jsanchez/Spectrum");
            openSnapshotDlg.setFileFilter(new FileFilterSnapshot());
            currentDirOpenSnapshot = openSnapshotDlg.getCurrentDirectory();
        }
        else
            openSnapshotDlg.setCurrentDirectory(currentDirOpenSnapshot);

        if (!paused)
            spectrum.stopEmulation();

        int status = openSnapshotDlg.showOpenDialog(getContentPane());
        if( status == JFileChooser.APPROVE_OPTION ) {
            //spectrum.stopEmulation();
            currentDirOpenSnapshot = openSnapshotDlg.getCurrentDirectory();
            spectrum.loadSnapshot(openSnapshotDlg.getSelectedFile());
        }
        if (!paused)
            spectrum.startEmulation();
    }//GEN-LAST:event_fileOpenSnapshotActionPerformed

    private void thisIsTheEndMyFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thisIsTheEndMyFriendActionPerformed
        // TODO add your handling code here:
        ResourceBundle bundle = ResourceBundle.getBundle("gui/Bundle"); // NOI18N
        int ret = JOptionPane.showConfirmDialog(getContentPane(),
                  bundle.getString("ARE_YOU_SURE_QUESTION"), bundle.getString("QUIT_JSPECCY"),
                  JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE); // NOI18N
        if( ret == JOptionPane.YES_OPTION ) {
            spectrum.stopEmulation();
            System.exit(0);
        }
    }//GEN-LAST:event_thisIsTheEndMyFriendActionPerformed

    private void doubleSizeOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleSizeOptionActionPerformed
        Object source = evt.getSource();
        if( source instanceof javax.swing.JCheckBoxMenuItem )
            doubleSizeToggleButton.setSelected(doubleSizeOption.isSelected());
        else
            doubleSizeOption.setSelected(doubleSizeToggleButton.isSelected());

        jscr.toggleDoubleSize();
        pack();
    }//GEN-LAST:event_doubleSizeOptionActionPerformed

    private void pauseMachineMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseMachineMenuActionPerformed
        Object source = evt.getSource();
        if( source instanceof javax.swing.JCheckBoxMenuItem )
            pauseToggleButton.setSelected(pauseMachineMenu.isSelected());
        else
            pauseMachineMenu.setSelected(pauseToggleButton.isSelected());
        
        if( pauseMachineMenu.isSelected() )
            spectrum.stopEmulation();
        else
            spectrum.startEmulation();
    }//GEN-LAST:event_pauseMachineMenuActionPerformed

    private void resetMachineMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetMachineMenuActionPerformed
        ResourceBundle bundle = ResourceBundle.getBundle("gui/Bundle"); // NOI18N
        int ret = JOptionPane.showConfirmDialog(getContentPane(),
                  bundle.getString("ARE_YOU_SURE_QUESTION"), bundle.getString("RESET_SPECTRUM"),
                  JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE); // NOI18N

        if( ret == JOptionPane.YES_OPTION )
            spectrum.reset();
    }//GEN-LAST:event_resetMachineMenuActionPerformed

    private void silenceSoundToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silenceSoundToggleButtonActionPerformed
        Object source = evt.getSource();
        if( source instanceof javax.swing.JToggleButton )
            silenceMachineMenu.setSelected(silenceSoundToggleButton.isSelected());
        else
            silenceSoundToggleButton.setSelected(silenceMachineMenu.isSelected());

        spectrum.toggleSound();
    }//GEN-LAST:event_silenceSoundToggleButtonActionPerformed

    private void playTapeMediaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playTapeMediaMenuActionPerformed
        spectrum.toggleTape();
    }//GEN-LAST:event_playTapeMediaMenuActionPerformed

    private void openTapeMediaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openTapeMediaMenuActionPerformed
        boolean paused = spectrum.isPaused();
        if( OpenTapeDlg == null ) {
            OpenTapeDlg = new JFileChooser("/home/jsanchez/Spectrum");
            OpenTapeDlg.setFileFilter(new FileFilterTape());
            currentDirTape = OpenTapeDlg.getCurrentDirectory();
        }
        else
            OpenTapeDlg.setCurrentDirectory(currentDirTape);

        if (!paused)
            spectrum.stopEmulation();

        int status = OpenTapeDlg.showOpenDialog(getContentPane());
        if( status == JFileChooser.APPROVE_OPTION ) {
            //spectrum.stopEmulation();
            currentDirTape = OpenTapeDlg.getCurrentDirectory();
            spectrum.tape.eject();
            spectrum.tape.insert(OpenTapeDlg.getSelectedFile());
            tapeFilename.setText(OpenTapeDlg.getSelectedFile().getName());
        }
        if (!paused)
            spectrum.startEmulation();
    }//GEN-LAST:event_openTapeMediaMenuActionPerformed

    private void rewindTapeMediaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rewindTapeMediaMenuActionPerformed
        spectrum.tape.rewind();
    }//GEN-LAST:event_rewindTapeMediaMenuActionPerformed

    private void imageHelpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageHelpMenuActionPerformed
        keyboardHelper.setResizable(false);
        keyboardHelper.pack();
        keyboardHelper.setVisible(true);
    }//GEN-LAST:event_imageHelpMenuActionPerformed

    private void aboutHelpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutHelpMenuActionPerformed
        ResourceBundle bundle = ResourceBundle.getBundle("gui/Bundle"); // NOI18N
        JOptionPane.showMessageDialog(getContentPane(),
            bundle.getString("ABOUT_MESSAGE"), bundle.getString("ABOUT_TITLE"),
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_aboutHelpMenuActionPerformed

    private void nmiMachineMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmiMachineMenuActionPerformed
        spectrum.triggerNMI();
    }//GEN-LAST:event_nmiMachineMenuActionPerformed

    private void closeKeyboardHelperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeKeyboardHelperActionPerformed
        keyboardHelper.setVisible(false);
    }//GEN-LAST:event_closeKeyboardHelperActionPerformed

    private void fileSaveSnapshotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileSaveSnapshotActionPerformed
        // TODO add your handling code here:
        boolean paused = spectrum.isPaused();
        if( saveSnapshotDlg == null ) {
            saveSnapshotDlg = new JFileChooser("/home/jsanchez/Spectrum");
            saveSnapshotDlg.setFileFilter(new FileFilterSnapshot());
            currentDirSaveSnapshot = saveSnapshotDlg.getCurrentDirectory();
        }
        else {
            saveSnapshotDlg.setCurrentDirectory(currentDirSaveSnapshot);
            BasicFileChooserUI chooserUI = (BasicFileChooserUI) saveSnapshotDlg.getUI();
            chooserUI.setFileName("");
        }

        if (!paused)
            spectrum.stopEmulation();

        int status = saveSnapshotDlg.showSaveDialog(getContentPane());
        if( status == JFileChooser.APPROVE_OPTION ) {
            //spectrum.stopEmulation();
            currentDirSaveSnapshot = saveSnapshotDlg.getCurrentDirectory();
            spectrum.saveSnapshot(saveSnapshotDlg.getSelectedFile());
        }
        if (!paused)
            spectrum.startEmulation();
    }//GEN-LAST:event_fileSaveSnapshotActionPerformed

    private void noneJoystickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noneJoystickActionPerformed

        spectrum.setJoystick(Spectrum.Joystick.NONE);

}//GEN-LAST:event_noneJoystickActionPerformed

    private void kempstonJoystickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kempstonJoystickActionPerformed

        spectrum.setJoystick(Spectrum.Joystick.KEMPSTON);

    }//GEN-LAST:event_kempstonJoystickActionPerformed

    private void sinclair1JoystickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinclair1JoystickActionPerformed

        spectrum.setJoystick(Spectrum.Joystick.SINCLAIR1);

    }//GEN-LAST:event_sinclair1JoystickActionPerformed

    private void sinclair2JoystickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinclair2JoystickActionPerformed

        spectrum.setJoystick(Spectrum.Joystick.SINCLAIR2);

    }//GEN-LAST:event_sinclair2JoystickActionPerformed

    private void cursorJoystickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursorJoystickActionPerformed

        spectrum.setJoystick(Spectrum.Joystick.CURSOR);
        
    }//GEN-LAST:event_cursorJoystickActionPerformed

    private void spec48kHardwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spec48kHardwareActionPerformed
        boolean paused = spectrum.isPaused();

        if (!paused)
            spectrum.stopEmulation();

        spectrum.select48kHardware();
        spectrum.reset();

        if (!paused)
            spectrum.startEmulation();
    }//GEN-LAST:event_spec48kHardwareActionPerformed

    private void spec128kHardwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spec128kHardwareActionPerformed
        boolean paused = spectrum.isPaused();

        if (!paused)
            spectrum.stopEmulation();

        spectrum.select128kHardware();
        spectrum.reset();

        if (!paused)
            spectrum.startEmulation();
    }//GEN-LAST:event_spec128kHardwareActionPerformed

    private void fastEmulationToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fastEmulationToggleButtonActionPerformed
        spectrum.toggleSpeed();
    }//GEN-LAST:event_fastEmulationToggleButtonActionPerformed

    private void browserTapeMediaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browserTapeMediaMenuActionPerformed
        //tapeBrowser.validate();
        tapeBrowserDialog.setVisible(true);
        tapeBrowserDialog.pack();
        tapeCatalog.doLayout();
    }//GEN-LAST:event_browserTapeMediaMenuActionPerformed

    private void closeTapeBrowserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeTapeBrowserButtonActionPerformed
        tapeBrowserDialog.setVisible(false);
//        int row = tapeCatalog.getSelectedRow();
//        if (row != -1) {
//            spectrum.tape.setSelectedBlock(row);
//        }
    }//GEN-LAST:event_closeTapeBrowserButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JSpeccy().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutHelpMenu;
    private javax.swing.JMenuItem browserTapeMediaMenu;
    private javax.swing.JButton closeKeyboardHelper;
    private javax.swing.JButton closeTapeBrowserButton;
    private javax.swing.JRadioButtonMenuItem cursorJoystick;
    private javax.swing.JCheckBoxMenuItem doubleSizeOption;
    private javax.swing.JToggleButton doubleSizeToggleButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JToggleButton fastEmulationToggleButton;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem fileOpenSnapshot;
    private javax.swing.JMenuItem fileSaveSnapshot;
    private javax.swing.ButtonGroup hardwareButtonGroup;
    private javax.swing.JMenu hardwareMachineMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem imageHelpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.ButtonGroup joystickButtonGroup;
    private javax.swing.JMenu joystickOptionMenu;
    private javax.swing.JRadioButtonMenuItem kempstonJoystick;
    private javax.swing.JDialog keyboardHelper;
    private javax.swing.JLabel keyboardImage;
    private javax.swing.JMenu machineMenu;
    private javax.swing.JMenu mediaMenu;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JMenuItem nmiMachineMenu;
    private javax.swing.JRadioButtonMenuItem noneJoystick;
    private javax.swing.JButton openSnapshotButton;
    private javax.swing.JMenuItem openTapeMediaMenu;
    private javax.swing.JMenu optionsMenu;
    private javax.swing.JCheckBoxMenuItem pauseMachineMenu;
    private javax.swing.JToggleButton pauseToggleButton;
    private javax.swing.JMenuItem playTapeMediaMenu;
    private javax.swing.JMenuItem resetMachineMenu;
    private javax.swing.JButton resetSpectrumButton;
    private javax.swing.JMenuItem rewindTapeMediaMenu;
    private javax.swing.JCheckBoxMenuItem silenceMachineMenu;
    private javax.swing.JToggleButton silenceSoundToggleButton;
    private javax.swing.JRadioButtonMenuItem sinclair1Joystick;
    private javax.swing.JRadioButtonMenuItem sinclair2Joystick;
    private javax.swing.JRadioButtonMenuItem spec128kHardware;
    private javax.swing.JRadioButtonMenuItem spec48kHardware;
    private javax.swing.JLabel speedLabel;
    private javax.swing.JDialog tapeBrowserDialog;
    private javax.swing.JTable tapeCatalog;
    private javax.swing.JLabel tapeFilename;
    private javax.swing.JLabel tapeLabel;
    private javax.swing.JMenu tapeMediaMenu;
    private javax.swing.JMenuItem thisIsTheEndMyFriend;
    private javax.swing.JToolBar toolbarMenu;
    // End of variables declaration//GEN-END:variables
    
}
