/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoadSaveMemoryDialog.java
 *
 * Created on 19-dic-2011, 13:01:51
 */
package gui;

import java.awt.Component;
import java.awt.Frame;
import java.io.File;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import machine.Memory;

/**
 *
 * @author jsanchez
 */
public class LoadSaveMemoryDialog extends javax.swing.JPanel {

    private JDialog loadSaveMemoryDialog;
    private JFileChooser fileDlg;
    FileNameExtensionFilter binExtension;
    private Memory memory;
    private File filename;
    private boolean saveDialog;

    /** Creates new form LoadSaveMemoryDialog */
    public LoadSaveMemoryDialog(Memory memory) {
        this.memory = memory;
        initComponents();
        binExtension = new FileNameExtensionFilter(
            java.util.ResourceBundle.getBundle("gui/Bundle").getString("BINARY_EXTENSION_TYPE"), "bin");
    }

    public boolean showLoadDialog(Component parent) {
        Frame owner = null;
        if (parent instanceof Frame) {
            owner = (Frame) parent;
        } else {
            owner = (Frame) SwingUtilities.getAncestorOfClass(Frame.class, parent);
        }

        if (loadSaveMemoryDialog == null) {
            loadSaveMemoryDialog = new JDialog(owner, false);
//            loadSaveMemoryDialog.setMinimumSize(new Dimension(30, 200));
//            loadSaveMemoryDialog.setMaximumSize(new Dimension(520, 800));
            loadSaveMemoryDialog.getContentPane().add(this);
            loadSaveMemoryDialog.pack();
        }

        saveDialog = false;
        filename = null;
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("gui/Bundle"); // NOI18N
        closeButton.setText(bundle.getString("LoadSaveMemoryDialog.closeButton.text"));
        loadSaveMemoryDialog.setTitle(bundle.getString("LoadSaveMemoryDialog.LoadTile.text"));
        addressSpinner.setEnabled(false);
        sizeSpinner.setEnabled(false);
        rangeCombobox.setEnabled(false);
        loadSaveMemoryDialog.setVisible(true);
        return true;
    }

    public boolean showSaveDialog(Component parent) {
        Frame owner = null;
        if (parent instanceof Frame) {
            owner = (Frame) parent;
        } else {
            owner = (Frame) SwingUtilities.getAncestorOfClass(Frame.class, parent);
        }

        if (loadSaveMemoryDialog == null) {
            loadSaveMemoryDialog = new JDialog(owner, false);
//            loadSaveMemoryDialog.setMinimumSize(new Dimension(30, 200));
//            loadSaveMemoryDialog.setMaximumSize(new Dimension(520, 800));
            loadSaveMemoryDialog.getContentPane().add(this);
            loadSaveMemoryDialog.pack();
        }

        saveDialog = true;
        filename = null;
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("gui/Bundle"); // NOI18N
        closeButton.setText(bundle.getString("LoadSaveMemoryDialog.closeButton.text"));
        loadSaveMemoryDialog.setTitle(bundle.getString("LoadSaveMemoryDialog.SaveTile.text"));
        addressSpinner.setEnabled(false);
        sizeSpinner.setEnabled(false);
        rangeCombobox.setEnabled(false);
        loadSaveMemoryDialog.setVisible(true);
        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChoosedLabel = new javax.swing.JLabel();
        browseButton = new javax.swing.JButton();
        addressLabel = new javax.swing.JLabel();
        addressSpinner = new javax.swing.JSpinner();
        sizeLabel = new javax.swing.JLabel();
        sizeSpinner = new javax.swing.JSpinner();
        rangeLabel = new javax.swing.JLabel();
        rangeCombobox = new javax.swing.JComboBox();
        closeButton = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("gui/Bundle"); // NOI18N
        fileChoosedLabel.setText(bundle.getString("LoadSaveMemoryDialog.fileChoosedLabel.text")); // NOI18N

        browseButton.setText(bundle.getString("LoadSaveMemoryDialog.browseButton.text")); // NOI18N
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        addressLabel.setText(bundle.getString("LoadSaveMemoryDialog.addressLabel.text")); // NOI18N

        addressSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 65535, 1));

        sizeLabel.setText(bundle.getString("LoadSaveMemoryDialog.sizeLabel.text")); // NOI18N

        sizeSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 65535, 1));

        rangeLabel.setText(bundle.getString("LoadSaveMemoryDialog.rangeLabel.text")); // NOI18N

        rangeCombobox.setMaximumRowCount(9);
        rangeCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0x0000-0xFFFF", "RAM 0", "RAM 1", "RAM 2", "RAM 3", "RAM 4", "RAM 5", "RAM 6", "RAM 7" }));

        closeButton.setText(bundle.getString("LoadSaveMemoryDialog.closeButton.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(closeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rangeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rangeCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sizeSpinner)
                                    .addComponent(addressSpinner)))
                            .addComponent(fileChoosedLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(browseButton)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileChoosedLabel)
                    .addComponent(browseButton))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabel))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeLabel)
                    .addComponent(sizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rangeLabel)
                    .addComponent(rangeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(closeButton)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        if (fileDlg == null) {
            fileDlg = new JFileChooser("/home/jsanchez/Spectrum");
            fileDlg.addChoosableFileFilter(binExtension);
        }
        
        if (saveDialog) {
            int status = fileDlg.showSaveDialog(this);
        if (status == JFileChooser.APPROVE_OPTION) {
            if (binExtension.accept(fileDlg.getSelectedFile())) {
                filename = fileDlg.getSelectedFile();
            } else {
                String saveName = fileDlg.getSelectedFile().getAbsolutePath() + ".bin";
                filename = new File(saveName);
            }
        }
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JSpinner addressSpinner;
    private javax.swing.JButton browseButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel fileChoosedLabel;
    private javax.swing.JComboBox rangeCombobox;
    private javax.swing.JLabel rangeLabel;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JSpinner sizeSpinner;
    // End of variables declaration//GEN-END:variables
}
