/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MemoryBrowser.java
 *
 * Created on 23-nov-2011, 21:35:48
 */
package gui;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Frame;
import javax.swing.JDialog;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingUtilities;
import machine.Memory;
import tv.porst.jhexview.JHexView;
import tv.porst.jhexview.JHexView.DefinitionStatus;

/**
 *
 * @author jsanchez
 */
public class MemoryBrowserDialog extends javax.swing.JPanel {

    private JDialog memoryBrowserDialog;
    private JHexView hexView;
    
    /** Creates new form MemoryBrowser */
    public MemoryBrowserDialog(Memory memory) {
        initComponents();
        hexView = new JHexView();
        hexView.setData(memory);
        hexView.setDefinitionStatus(DefinitionStatus.DEFINED);
        hexView.setBytesPerColumn(1);
        hexView.setEnabled(true);
        hexViewPanel.add(hexView);
    }

    public boolean showDialog(Component parent, String title) {
        Frame owner = null;
        if (parent instanceof Frame) {
            owner = (Frame) parent;
        } else {
            owner = (Frame) SwingUtilities.getAncestorOfClass(Frame.class, parent);
        }

        if (memoryBrowserDialog == null) {
            memoryBrowserDialog = new JDialog(owner, false);
            memoryBrowserDialog.setMinimumSize(new Dimension(30,200));
            memoryBrowserDialog.getContentPane().add(this); 
            memoryBrowserDialog.pack();
        }
        
        memoryBrowserDialog.setTitle(title);
        memoryBrowserDialog.setVisible(true);
        return true;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hexViewPanel = new javax.swing.JPanel();
        optionsPanel = new javax.swing.JPanel();
        decimalAddress = new javax.swing.JCheckBox();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(16, 25), new java.awt.Dimension(16, 25), new java.awt.Dimension(16, 25));
        gotoAddressLabel = new javax.swing.JLabel();
        gotoAddress = new javax.swing.JSpinner();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        closePanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(100, 200));
        setPreferredSize(new java.awt.Dimension(501, 341));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        hexViewPanel.setMinimumSize(new java.awt.Dimension(50, 50));
        hexViewPanel.setPreferredSize(new java.awt.Dimension(495, 300));
        hexViewPanel.setLayout(new javax.swing.BoxLayout(hexViewPanel, javax.swing.BoxLayout.LINE_AXIS));
        add(hexViewPanel);

        optionsPanel.setPreferredSize(new java.awt.Dimension(495, 50));
        optionsPanel.setLayout(new javax.swing.BoxLayout(optionsPanel, javax.swing.BoxLayout.LINE_AXIS));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("gui/Bundle"); // NOI18N
        decimalAddress.setText(bundle.getString("MemoryBrowserDialog.decimalAddress.txt")); // NOI18N
        decimalAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalAddressActionPerformed(evt);
            }
        });
        optionsPanel.add(decimalAddress);
        optionsPanel.add(filler2);

        gotoAddressLabel.setText(bundle.getString("MemoryBrowserDialog.gotoAddress.txt")); // NOI18N
        optionsPanel.add(gotoAddressLabel);

        gotoAddress.setModel(new javax.swing.SpinnerNumberModel(0, 0, 65535, 1));
        gotoAddress.setMaximumSize(new java.awt.Dimension(27, 20));
        gotoAddress.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                gotoAddressStateChanged(evt);
            }
        });
        optionsPanel.add(gotoAddress);
        optionsPanel.add(filler1);

        add(optionsPanel);

        closePanel.setPreferredSize(new java.awt.Dimension(495, 70));
        closePanel.setLayout(new javax.swing.BoxLayout(closePanel, javax.swing.BoxLayout.LINE_AXIS));

        closeButton.setText(bundle.getString("MemoryBrowser.closeButton.text")); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        closePanel.add(closeButton);

        add(closePanel);
    }// </editor-fold>//GEN-END:initComponents

    private void decimalAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalAddressActionPerformed
        hexView.setAddressMode(decimalAddress.isSelected() ?
                JHexView.AddressMode.DECIMAL : JHexView.AddressMode.HEXADECIMAL);
    }//GEN-LAST:event_decimalAddressActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        memoryBrowserDialog.setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void gotoAddressStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_gotoAddressStateChanged
        SpinnerNumberModel snmAddress = (SpinnerNumberModel)gotoAddress.getModel();
        hexView.gotoOffset(snmAddress.getNumber().longValue() & 0xffff);
    }//GEN-LAST:event_gotoAddressStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel closePanel;
    private javax.swing.JCheckBox decimalAddress;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JSpinner gotoAddress;
    private javax.swing.JLabel gotoAddressLabel;
    private javax.swing.JPanel hexViewPanel;
    private javax.swing.JPanel optionsPanel;
    // End of variables declaration//GEN-END:variables
}
